### ISSUE TITLE
Unable to create a new reminder

### ISSUE THREAD

**Issue by alaq** [MauriceConrad/iCloud-API#19]
I have been unable to create a reminder, using the example code.

I get the following stack trace: 
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (./node_modules/apple-icloud/resources/apps/Reminders.js:110:35)
    at Request.self.callback (./node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (./node_modules/request/request.js:1161:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (./node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:281:20)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
```

which is because `body` is an empty string here: https://github.com/MauriceConrad/iCloud-API/blob/master/resources/apps/Reminders.js#L110

I am trying to troubleshoot this (changing a task works, for instance) but any help would be appreciated, thanks!

**Comment by MauriceConrad** [comment]
Fixed
