### ISSUE TITLE
Example code failing with TypeError

### ISSUE THREAD

**Issue by nucks** [MauriceConrad/iCloud-API#46]
A TypeError is thrown from running your example login code
```
You are logged in successfully!
(node:10120) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'ckdatabasews' of undefined
    at iCloud.__zone /Documents/noteconverter/node_modules/apple-icloud/resources/apps/Notes.js:178:63)
    at Object.main.<computed> [as __zone] (/Documents/noteconverter/node_modules/apple-icloud/resources/helper.js:84:27)
    at iCloud.fetch (/Documents/noteconverter/node_modules/apple-icloud/resources/apps/Notes.js:62:16)
    at Object.main.<computed> [as fetch] (/Documents/noteconverter/node_modules/apple-icloud/resources/helper.js:84:27)
    at iCloud.<anonymous> (/Documents/noteconverter/prompt-credentials.js:37:37)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:10120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the code that is being run (along with `prompt-credentials.js`):
```
const promptiCloud = require("./prompt-credentials");

(async () => {
  // Login to icloud and ask for new credentials if needed
  const myCloud = await promptiCloud();

  // Get all notes
  const notes = myCloud.Notes.fetch();

  var done = false;

  notes.on("data", (zone) => {
    console.log(
      "Fetched: " +
        notes.__folders.length +
        " folders; " +
        notes.__notes.length +
        " notes"
    );

    // Log folders structured
    console.log(notes.folders);
  });
})();
```

**Comment by sandovalgus** [comment]
I think you should log in and enter the security code

````
var myCloud = new iCloud("icloud-session.json", username, password);
myCloud.on("ready", function() {
  console.log("Ready Event!");
  // Check if the two-factor-authentication is required
  if (myCloud.twoFactorAuthenticationIsRequired) {
    // Get the security code using node-prompt
    prompt.get(["Security Code"], async function(err, input) {
      if (err) return console.error(err);
      const code = input["Security Code"];
      // Set the security code to the instance
      myCloud.securityCode = code;
    });
  }
  else {
    // Now the 'ready' event fired but 'twoFactorAuthenticationIsRequired' is false, which means we don't need it (anymore)
    console.log("You are logged in completely!");
  }
});
```

**Comment by nucks** [comment]
@sandovalgus I am already doing this, with no luck. Is it working for you?
```
const iCloud = require("apple-icloud");

var prompt = require("prompt");

// Handles the requirement of two-factor-authentication
async function readyHandlerTwoFactor(myCloud) {
  if (myCloud.twoFactorAuthenticationIsRequired) {
    prompt.get(["Security Code"], function (err, input) {
      if (err) return console.error(err);f
      const code = input["Security Code"];
      myCloud.securityCode = code;
    });
    return false;
  } else {
    console.log("You are logged in successfully!");

    return true;
  }
}

const sessionPath = "/tmp/icloud-session.json";

module.exports = function login() {
  return new Promise(function (resolve, reject) {
    prompt.start();

    var myCloud = new iCloud(sessionPath);
    myCloud.on("ready", async function () {
      // Returns
      const isAutheticated = await readyHandlerTwoFactor(myCloud);
      if (isAutheticated) {
        const notes = myCloud.Notes.fetch();

        notes.on("data", (zone) => {
          // Do not use zone by default, the notes are sorted into 'folders'

          // 'folders' is an array containing all notes sorted by folders that are known at this point of time
          // Because of the fact, that the folders are coming over a zone, it may takes some time
          console.log(notes.folders);

          // Just log the notes you already got
          //console.log(notes.__notes);
        });

        notes.on("end", () => {
          // Now, you can be sure that EACH folder and EACH note are known
          console.log(note.folders);
        });

        resolve(myCloud);
      }
    });
    myCloud.on("err", function (err) {
      if (err.errorCode == 6) {
        //console.error("Given session does not eixst or is expired. Try to use contained credentials from session to re-login...");
      }
      // Error code 7: Invalid credentials or borken account
      if (err.errorCode == 7) {
        console.error(
          "The contained credentials are not correct or the given session does not exist/is broken."
        );
        // Try to get new credentials
        console.log("\nPlease log in with your credentials! (Username = Mail)");

        prompt.get(
          {
            properties: {
              username: {
                pattern: /^.*$/,
                message: "Mail",
                required: false,
              },
              password: {
                required: false,
                hidden: true,
              },
            },
          },
          function (err, input) {
            if (err) return console.error(err);

            // This creates your iCloud instance
            var myCloud = new iCloud(
              sessionPath,
              input.username,
              input.password
            );

            myCloud.on("ready", async function () {
              const isAutheticated = await readyHandlerTwoFactor(myCloud);
              if (isAutheticated) {
                resolve(myCloud);
              }
            });

            myCloud.on("sessionUpdate", function () {
              myCloud.saveSession();
            });
          }
        );
      }
    });
  });
};```

**Comment by bugs181** [comment]
@nucks why did you close this issue? I'm having this exact problem. If you fixed it, please provide how you did so.

**Comment by nucks** [comment]
@bugs181 I can't remember why I closed it. From what I do remember, I don't think I was able to ever get it working correctly.

**Comment by guyzyl** [comment]
@bugs181 Have you found out what the issue was?

**Comment by bugs181** [comment]
> @bugs181 Have you found out what the issue was?

Unfortunately, no. And I also stopped using iCloud. Sorry I can't be of more help.
