### ISSUE TITLE
It seems that `self.account.webservices` is undefined when `getHostFromWebservice` is called

### ISSUE THREAD

**Issue by oitan** [MauriceConrad/iCloud-API#53]
I tried to run the demos and got this for `getOpenTasks` and similar to this  for `getCollections`:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'reminders' of undefined
    at iCloud.getOpenTasks (......./node_modules/apple-icloud/resources/apps/Reminders.js:7:63)
    at Object.main.<computed> [as getOpenTasks] (......./node_modules/apple-icloud/resources/helper.js:84:27)
```
I am not sure if it's because Apple's API is updated or not. If you can give me directions, I could make a pr too to contribute.

**Comment by JulianNeigenfind** [comment]
Similar issue in FindMe.get
